- key: 'parentholder'
  title: "The patent holder\u2019s dilemma: Buy, sell, or troll?"
  authors: "Patricia S. Abril and Robert Plant"
  publish_date: "2007"
  publish_location: "Commun. ACM 50, 1 (Jan. 2007),"
  publisher: "ACM 50"
  url: "http://dx.doi.org/10.1145/1188913.1188915"

- key: 'test'
  title: "The patent holder\u2019s dilemma: Buy, sell, or troll?"
  authors: "Patricia S. Abril and Robert Plant"
  publish_date: "2007"
  publish_location: "Commun. ACM 50, 1 (Jan. 2007),"
  publisher: "ACM 50"
  url: "http://dx.doi.org/10.1145/1188913.1188915"
